### ISSUE TITLE
【置顶】网站无法打开

### ISSUE THREAD

**Issue by gfxcc** [gfxcc/san11-platform#1]
目前网站的服务器架设在AWS @ HK. 
国内用户访问HK服务器不太稳定。（有的国内用户表示很快，有的国内用户表示无法访问）

后续会继续努力解决这一问题。

如果您也遇到了网站无法访问的问题，可以在这里回复一些具体信息帮助我们定位网络问题。

【回复格式】
问题：网站无法打开/网站访问过慢（xx秒）
运营商：电信/移动/联通
地址：中国，江苏 / 美国 / ...

**Comment by GuangZhiShi** [comment]
【回复格式】
问题：网站无法打开
地址：中国，广东 
ping连接约200ms，不波动
